root = "."
tmp_dir = "tmp"

[build] # Build configuration
    bin = "main"
    cmd = "go build -o {{.Output}} {{.Input}}"
    exclude = ["tmp/","client/"]
    include = ["**/*.go"]
    ignore = ["tmp/*"]
